/** Map sidebar paths to their lazy route chunks for hover prefetch. */
const ROUTE_PREFETCHERS: Record<string, () => Promise<unknown>> = {
  "/chat": () => import("../pages/Chat"),
  "/experts": () => import("../pages/Experts"),
  "/tasks": () => import("../pages/Projects"),
  "/projects": () => import("../pages/Projects"),
  "/models": () => import("../pages/Settings/Models"),
  "/connectors": () => import("../pages/Agent/Personalization"),
  "/skill-packages": () => import("../pages/Agent/Personalization"),
  "/knowledge-bases": () => import("../pages/KnowledgeBases"),
  "/skills": () => import("../pages/Agent/Personalization"),
  "/token-usage": () => import("../pages/Control/TokenUsage"),
  "/channels": () => import("../pages/Agent/Personalization"),
  "/workbench": () => import("../pages/Control/Workbench"),
  "/workbench/browser": () => import("../pages/Control/Workbench"),
  "/workbench/terminal": () => import("../pages/Control/Workbench"),
  "/remote-desktop": () => import("../pages/Control/RemoteDesktop"),
  "/remote-desktop/desktop": () => import("../pages/Control/RemoteDesktop"),
  "/remote-desktop/phone": () => import("../pages/Control/RemoteDesktop"),
  "/remote-phone": () => import("../pages/Control/RemoteDesktop"),
  "/remote-android": () => import("../pages/Control/RemoteDesktop"),
  "/acp": () => import("../pages/Agent/Personalization"),
  "/system-settings": () => import("../pages/Agent/Personalization"),
  "/personalization": () => import("../pages/Agent/Personalization"),
  "/personalization/skills": () => import("../pages/Agent/Personalization"),
  "/personalization/tools": () => import("../pages/Agent/Personalization"),
  "/personalization/subagents": () => import("../pages/Agent/Personalization"),
  "/personalization/channels": () => import("../pages/Agent/Personalization"),
  "/personalization/mbti": () => import("../pages/Agent/Personalization"),
  "/personalization/memory": () => import("../pages/Agent/Personalization"),
  "/subagents": () => import("../pages/Agent/Personalization"),
  "/mbti": () => import("../pages/Agent/Personalization"),
  "/memory": () => import("../pages/Agent/Personalization"),
  "/admin/models": () => import("../pages/Settings/Models"),
  "/admin/users": () => import("../pages/Agent/Personalization"),
  "/admin/backend": () => import("../pages/Agent/Personalization"),
  "/admin/plugins": () => import("../pages/Agent/Personalization"),
  "/admin/security": () => import("../pages/Agent/Personalization"),
  "/admin/advanced": () => import("../pages/Agent/Personalization"),
  "/agent-config": () => import("../pages/Agent/Personalization"),
};

export function prefetchRoute(path: string): void {
  const load = ROUTE_PREFETCHERS[path];
  if (load) void load();
}
