export type Locale = "zh" | "en";

export const LINKS = {
  site: "https://freeos.cnxy.tech",
  github: "https://github.com/XYAIStudio/FreeOS",
  releases: "https://github.com/XYAIStudio/FreeOS/releases",
  releaseTag: "https://github.com/XYAIStudio/FreeOS/releases/latest",
  windowsAmd64:
    "https://github.com/XYAIStudio/FreeOS/releases/download/v0.0.3/FreeOS-desktop-windows-amd64-0.0.3.exe",
  windowsArm64:
    "https://github.com/XYAIStudio/FreeOS/releases/download/v0.0.3/FreeOS-desktop-windows-arm64-0.0.3.exe",
  productContract:
    "https://github.com/XYAIStudio/FreeOS/blob/main/docs/product-contract.zh-CN.md",
  openxyos: "https://github.com/XYAIStudio/openXYOS",
  openxyosSite: "https://openxyos.cnxy.tech/?lang=zh-CN",
  octopUpstream: "https://github.com/TencentCloud/Octop",
  notice: "https://github.com/XYAIStudio/FreeOS/blob/main/NOTICE",
  architecture:
    "https://github.com/XYAIStudio/FreeOS/blob/main/docs/architecture-integration.md",
  assetLoop: "https://github.com/XYAIStudio/FreeOS/blob/main/docs/asset-loop.md",
} as const;

export const copy = {
  zh: {
    langName: "中文",
    skip: "跳到正文",
    nav: {
      engines: "双引擎",
      capabilities: "能力",
      download: "下载",
      loop: "闭环",
      faq: "问答",
    },
    stackHead: {
      kicker: "00 / 节奏",
      title: "数据面、控制面、自生长闭环",
      lead: "一层把同事跑在你的机器上，一层用蓝图和治理把组织养大，一条闭环让下一轮自己长出来。",
    },
    stack: [
      { no: "CORE 00", layer: "底座", name: "FreeOS 数据面", text: "把智能体跑在你自己的机器上。" },
      { no: "SYSTEM 01", layer: "系统", name: "openXYOS 控制面", text: "用蓝图、治理和人才市场把同事养大。" },
      { no: "LOOP ∞", layer: "生态", name: "自生长闭环", text: "生产、装配、回馈，下一轮自己长出来。" },
    ],
    manifesto: "把工作室安在自己的电脑上，让组织自己长出下一位同事。",
    brandAlt: "FreeOS 圆形标志：灰环、黄绿红勾玉、蓝色水滴",
    hero: {
      eyebrow: "FreeOS · 开源 · 自托管 · 最新 Release",
      title: "FreeOS",
      headline: ["FreeOS：自由的 AI 工作室", "想象空间由你来打开"],
      promise: "Octop 的对话与自动化",
      times: "×",
      org: "openXYOS 的组织与治理",
      lead: "先在本机安顿好的工作室：注册登录、数据与会话留在你够得着的地方。组织像另一间可独立布置的房间，与日常对话、助手同在一个 FreeOS 里。",
      download: "下载 Windows 安装包",
      github: "打开 GitHub",
      chips: ["可验证", "可交付", "数据本地"],
      mascotHint: "点一下换个姿态",
      mascotAlt: "XYAI 机器人欢迎姿态",
    },
    proof: {
      kicker: "看得见 · 验得过 · 可决定",
      title: "每一步都看得见、验得过、可决定",
      items: [
        { title: "看得见", text: "先在本机安顿好：打开就能聊，不必先登录。" },
        { title: "验得过", text: "出站、删除、支付、生产变更默认拒绝。" },
        { title: "可决定", text: "同一条动作经人批准，execute 才为 true。" },
      ],
    },
    engines: {
      kicker: "01 / 双引擎",
      title: "一间工作室，同时拥有对话与组织",
      lead: "日常房间里跑对话与助手，组织房间里养蓝图与治理。两边互补：一边生产会干活的智能体，一边用蓝图、治理和人才市场把它们养大，再喂回工作室。",
      dataTitle: "FreeOS 数据面",
      dataLicense: "MIT · 源自 Octop 运行时",
      dataBody: "多智能体聊天、技能、插件、MCP、记忆、定时任务、工作区与飞书 / 钉钉 / Discord 等 IM——真正把同事跑起来的那一层。",
      controlTitle: "openXYOS 控制面",
      controlLicense: "Apache-2.0 · 组织操作系统",
      controlBody: "多租户、组织建模、模块目录、智能体蓝图、治理引擎与人才市场——决定谁能进组织、能做什么、如何升级。",
      flowOut: "生产 AI 员工 · 技能 · 插件 · MCP",
      flowAssemble: "装配进 openXYOS 模块与人才市场",
      flowBack: "蓝图 · 治理 · 人才回馈",
      flowSpawn: "再孵化或升级运行时智能体",
      note: "对话与助手仍在日常房间里跑；组织房间负责蓝图与治理。谢谢 Octop 与 openXYOS 把能力交到同一间工作室。",
    },
    capabilities: {
      kicker: "02 / 能力",
      title: "个人伙伴的手，组织操作系统的骨",
      lead: "可验证的运行时能力，加上可交付的组织治理。全部用 FreeOS 自己的语言来说。",
      groups: [
        {
          title: "数据面 · 把智能体跑在你机器上",
          items: [
            { tag: "RUNTIME", name: "多智能体", text: "每位用户可养多位同事：独立工作区、模型、人格与对话。" },
            { tag: "SKILL", name: "技能与插件", text: "SKILL.md、专家库、第三方插件，把一次性对话沉淀成可复用能力。" },
            { tag: "MCP", name: "MCP / 连接器", text: "OAuth 与 MCP 网关接入外部服务，工具走同一条审批路径。" },
            { tag: "MEMORY", name: "记忆与定时任务", text: "记忆随工作区迁移；Cron 把值班、汇报、巡检交给数字同事。" },
            { tag: "CHANNEL", name: "IM 通道", text: "飞书、钉钉、QQ、Discord、企业微信与控制台共用一条处理链路。" },
          ],
        },
        {
          title: "控制面 · 把同事放进可治理的组织",
          items: [
            { tag: "BLUEPRINT", name: "组织蓝图", text: "openxyos.agent-blueprint.v1 编译成可聊天的 FreeOS 智能体。" },
            { tag: "GOVERN", name: "治理与审批", text: "出站、删除、支付、生产变更默认拒绝，人批准后才 execute=true。" },
            { tag: "MODULE", name: "模块目录", text: "按租户启停模块；技能可发布为草稿，从不自动上线。" },
            { tag: "TALENT", name: "人才市场", text: "数字同事沿 draft → market → recruit → shadow → active 成长。" },
            { tag: "TENANT", name: "租户隔离", text: "一个租户一套工作区 / 沙箱，不靠提示词假装隔离。" },
          ],
        },
      ],
    },
    download: {
      kicker: "03 / 下载",
      title: "Windows 用户：下载、安装、打开即用",
      lead: "官网只负责介绍。从 GitHub 最新 Release 下载安装包，打开即可进入工作室：日常对话与组织控制台都在里面。第一次启动会解压内置环境，可能要一两分钟。组织运行时若随包装出现，是迁向宿主原生界面途中的过渡，不是终点。",
      amd64: "Windows 64 位",
      amd64Meta: "amd64 · .exe 安装包",
      arm64: "Windows ARM",
      arm64Meta: "arm64 · Surface / ARM 电脑",
      allReleases: "查看全部 Releases",
      stepsTitle: "四步开始",
      steps: [
        "打开最新 GitHub Release，下载 amd64 或 arm64 安装包。",
        "双击安装。程序会写入「程序文件」，并创建开始菜单与桌面快捷方式。",
        "打开 FreeOS。解压完成后直接进入可用会话——先聊，不必先登录。",
        "保存、导出或发布到账号时再注册。侧栏 Organization 默认打开。",
      ],
      dataNote: "数据默认在 %USERPROFILE%\\.freeos（可用 FREEOS_HOME 改）。卸载不会删除用户数据目录。",
      cliTitle: "开发者：一条命令跑通闭环",
      cliHint: "克隆仓库后：",
    },
    loop: {
      kicker: "04 / 闭环",
      title: "组织会自己长出下一位同事",
      lead: "freeos org loop run 是产品路径，不是演示脚本。它把蓝图变成可聊天的员工，走完生命周期，再把资产装回控制面，并证明高风险工具仍然被拦住。",
      steps: [
        { title: "生产", text: "数据面产出 AI 员工、技能、插件和 MCP，注册成真正能在聊天里叫到的智能体。" },
        { title: "装配", text: "资产打成 freeos.asset-pack.v1，写入 openXYOS 形状的员工、人才、插件与模块草稿。" },
        { title: "回馈", text: "组织树、蓝图、治理策略、模块目录和人才市场再进口到 FreeOS。" },
        { title: "升级", text: "下一位同事被孵化或升档。循环可重复，每次多一点可用能力。" },
      ],
      lifeTitle: "数字同事怎么转正",
      life: ["草稿", "上市", "招募", "见习", "在职", "离任"],
      lifeNote: "见习只读并受治理；转正后才打开岗位定时任务。离任会收回密钥，并把记忆归档到组织知识库。",
    },
    faq: {
      kicker: "05 / 问答",
      title: "工作室里的几件事",
      items: [
        {
          q: "FreeOS 和 Octop、openXYOS 是什么关系？",
          a: "FreeOS 把 Octop 的自托管多智能体能力与 openXYOS 的组织能力放进同一间工作室。运行基础来自 Octop（MIT），组织能力来自 openXYOS（Apache-2.0）。我们保留上游许可与致谢，用 FreeOS 自己的名字把它们养在一起。",
        },
        {
          q: "Windows 打开后为什么不用登录？",
          a: "先在本机安顿好：打开就能聊，数据与会话留在你够得着的地方。组织像工作室里另一间可独立布置的房间，方便试用与演练。更广的服务或授权以后会以可选方式慢慢打开，不挡你起步。",
        },
        {
          q: "我的对话和文件存在哪？",
          a: "默认 %USERPROFILE%\\.freeos。旧版 ~/.octop 仍会被识别。数据留在你的机器上，不经过 freeos.cnxy.tech。",
        },
        {
          q: "高风险操作真的会被拦住吗？",
          a: "会。出站、删除、支付、生产变更默认拒绝。必须有人批准同一条动作，execute 才会变成 true。侧车宕机也不会放行。",
        },
        {
          q: "许可证怎么选？",
          a: "宿主与桥接代码是 MIT；vendored 的 modules/openxyos 是 Apache-2.0。完整声明见仓库 NOTICE，请保留版权与许可文本。",
        },
        {
          q: "没有 Windows 也能用吗？",
          a: "可以。仓库提供源码路径：uv run freeos init && uv run freeos run。macOS / Linux 桌面包也在同一 Release。官网把 Windows 安装包放在最前面，因为那是非开发者的主路径。",
        },
      ],
    },
    cta: {
      title: "在自己的电脑上，养一支会成长的 AI 队伍",
      lead: "从 freeos.cnxy.tech 了解产品，到 GitHub 下载安装包，或从源码跑通 org loop。每一步都看得见、验得过、可决定。",
      download: "下载安装包",
      github: "Star / Fork",
      openxyos: "了解 openXYOS",
    },
    footer: {
      blurb: "自托管多智能体 OS，能生产并回收自己的 AI 员工。官网 freeos.cnxy.tech。",
      product: "产品",
      home: "官网",
      legal: "许可与致谢",
      links: {
        releases: "Releases",
        contract: "产品契约",
        docs: "集成架构",
        loop: "闭环说明",
        notice: "NOTICE",
        octop: "Octop 上游（MIT）",
        openxyos: "openXYOS（Apache-2.0）",
      },
      attrib:
        "感谢 Octop 贡献者（MIT）提供多智能体运行基础，感谢 openXYOS 贡献者（Apache-2.0）提供组织能力。FreeOS 是独立维护的下游项目，沿用上游许可并保留 NOTICE。残留的 octop 标识符只是兼容别名。",
      copyright: "© 2026 XYAI Labs 与 FreeOS 贡献者",
    },
  },
  en: {
    langName: "EN",
    skip: "Skip to content",
    nav: {
      engines: "Engines",
      capabilities: "Capabilities",
      download: "Download",
      loop: "The loop",
      faq: "FAQ",
    },
    stackHead: {
      kicker: "00 / Rhythm",
      title: "Data plane, control plane, self-growth loop",
      lead: "One layer runs colleagues on your machine. One layer raises the organization. One loop grows the next round.",
    },
    stack: [
      { no: "CORE 00", layer: "Base", name: "FreeOS data plane", text: "Run agents on your own machine." },
      { no: "SYSTEM 01", layer: "System", name: "openXYOS control plane", text: "Raise colleagues with blueprints, governance, and talent." },
      { no: "LOOP ∞", layer: "Loop", name: "Self-growth cycle", text: "Produce, assemble, feed back — the next round grows itself." },
    ],
    manifesto: "A studio on your own computer — an organization that grows its next colleague.",
    brandAlt: "FreeOS circular mark: gray ring, yellow green red magatama, blue teardrop",
    hero: {
      eyebrow: "FreeOS · Open source · Self-hosted · Latest release",
      title: "FreeOS",
      headline: ["Your FreeOS,", "free for you."],
      promise: "Chat and automation from Octop",
      times: "×",
      org: "organization and governance from openXYOS",
      lead: "A studio of your own — settle in locally first, with signup, login, data, and sessions within reach. Organization is another room you can arrange, sharing one FreeOS with everyday chat and assistants.",
      download: "Download for Windows",
      github: "View GitHub",
      chips: ["Verifiable", "Deliverable", "Data stays local"],
      mascotHint: "Tap to switch pose",
      mascotAlt: "XYAI robot in the welcome pose",
    },
    proof: {
      kicker: "Visible · Verifiable · Decidable",
      title: "Visible, verifiable, decidable — at every step",
      items: [
        { title: "Visible", text: "Settle in locally first: chat on open, no login wall." },
        { title: "Verifiable", text: "Outbound, delete, pay, and prod default-deny." },
        { title: "Decidable", text: "execute becomes true only after a human approves that same action." },
      ],
    },
    engines: {
      kicker: "01 / Engines",
      title: "One studio for conversation and organization",
      lead: "Everyday chat and assistants in one room; blueprints and governance in another. They complement each other: one produces working agents, the other raises them with blueprints, talent, and care, then feeds them back.",
      dataTitle: "FreeOS data plane",
      dataLicense: "MIT · derived from the Octop runtime",
      dataBody: "Multi-agent chat, skills, plugins, MCP, memory, cron, workspaces, and IM channels such as Feishu, DingTalk, and Discord — the layer that actually runs colleagues.",
      controlTitle: "openXYOS control plane",
      controlLicense: "Apache-2.0 · organization OS",
      controlBody: "Multi-tenancy, org modeling, module catalog, agent blueprints, governance, and the talent market — who joins, what they may do, how they level up.",
      flowOut: "Produce employees, skills, plugins, MCP",
      flowAssemble: "Assemble into openXYOS modules and talent",
      flowBack: "Blueprints, governance, talent feed back",
      flowSpawn: "Spawn or upgrade runtime agents",
      note: "Chat and assistants stay in the everyday room. The organization room holds blueprints and governance. Thanks to Octop and openXYOS for the capabilities that share this studio.",
    },
    capabilities: {
      kicker: "02 / Capabilities",
      title: "A companion’s hands. An organization OS’s bones.",
      lead: "A verifiable runtime, plus deliverable org governance — spoken in FreeOS’s own voice.",
      groups: [
        {
          title: "Data plane · agents on your machine",
          items: [
            { tag: "RUNTIME", name: "Multi-agent", text: "Each user can raise several colleagues, each with a workspace, model, persona, and threads." },
            { tag: "SKILL", name: "Skills & plugins", text: "SKILL.md, an expert library, and third-party plugins turn one-off chats into reusable capability." },
            { tag: "MCP", name: "MCP / connectors", text: "OAuth and an MCP gateway reach external services. Tools share one approval path." },
            { tag: "MEMORY", name: "Memory & cron", text: "Memory travels with the workspace. Cron hands patrols, reports, and shifts to digital colleagues." },
            { tag: "CHANNEL", name: "IM channels", text: "Feishu, DingTalk, QQ, Discord, WeCom, and the console share one processing pipeline." },
          ],
        },
        {
          title: "Control plane · colleagues inside a governed org",
          items: [
            { tag: "BLUEPRINT", name: "Org blueprints", text: "openxyos.agent-blueprint.v1 compiles into chat-ready FreeOS agents." },
            { tag: "GOVERN", name: "Governance", text: "Outbound, delete, pay, and prod stay denied until a human approves the same action digest." },
            { tag: "MODULE", name: "Module catalog", text: "Enable modules per tenant. Published skills stay drafts — never auto-on." },
            { tag: "TALENT", name: "Talent market", text: "Colleagues grow draft → market → recruit → shadow → active." },
            { tag: "TENANT", name: "Tenant isolation", text: "One tenant, one workspace/sandbox. Prompts are not a tenancy boundary." },
          ],
        },
      ],
    },
    download: {
      kicker: "03 / Download",
      title: "Windows: download, install, open, and use",
      lead: "This site introduces the product. Download the latest GitHub Release and open a studio: everyday chat and the organization console are both inside. First launch unpacks a runtime and may take a minute or two. If a managed organization runtime ships with the package, it is a bridge toward native host UI — not the destination.",
      amd64: "Windows 64-bit",
      amd64Meta: "amd64 · .exe installer",
      arm64: "Windows ARM",
      arm64Meta: "arm64 · Surface and ARM PCs",
      allReleases: "All releases",
      stepsTitle: "Four steps",
      steps: [
        "Open the latest GitHub Release and download the amd64 or arm64 installer.",
        "Run it. Files land in Program Files, with Start Menu and desktop shortcuts.",
        "Open FreeOS. After unpacking you land in a usable session — chat first, no login.",
        "Register only when you save, export, or publish to an account. Organization is on by default.",
      ],
      dataNote: "Data lives in %USERPROFILE%\\.freeos (override with FREEOS_HOME). Uninstall does not delete that directory.",
      cliTitle: "Developers: run the loop in one command",
      cliHint: "After cloning the repo:",
    },
    loop: {
      kicker: "04 / The loop",
      title: "The organization grows its next colleague",
      lead: "freeos org loop run is the product path, not a demo. It turns a blueprint into a chat-addressable employee, walks the lifecycle, applies assets back to the control plane, and proves high-risk tools still stop.",
      steps: [
        { title: "Produce", text: "The data plane emits employees, skills, plugins, and MCP, registered as real chat agents." },
        { title: "Assemble", text: "Packs become freeos.asset-pack.v1 and land on openXYOS-shaped employee, talent, plugin, and module drafts." },
        { title: "Feed back", text: "Org tree, blueprints, policies, the module catalog, and talent import back into FreeOS." },
        { title: "Upgrade", text: "The next colleague is spawned or promoted. Repeat. Each cycle adds usable capability." },
      ],
      lifeTitle: "How a digital colleague is promoted",
      life: ["Draft", "Market", "Recruit", "Shadow", "Active", "Offboard"],
      lifeNote: "Shadow is read-only and governed. Cron from job duties turns on only when active. Offboard revokes secrets and archives memory into org knowledge.",
    },
    faq: {
      kicker: "05 / FAQ",
      title: "A few things about the studio",
      items: [
        {
          q: "How does FreeOS relate to Octop and openXYOS?",
          a: "FreeOS brings Octop’s self-hosted multi-agent runtime and openXYOS organization capabilities into one studio. The runtime is derived from Octop (MIT); organization capabilities come from openXYOS (Apache-2.0). We keep upstream licenses and credit, and present the product under the FreeOS name.",
        },
        {
          q: "Why is there no login on first launch?",
          a: "Settle in locally first: open and chat, with data and sessions within reach. Organization is another room you can arrange for trying and rehearsing. Broader services or licensing can open later as options — never as a gate at the start.",
        },
        {
          q: "Where do chats and files live?",
          a: "Default %USERPROFILE%\\.freeos. Legacy ~/.octop is still recognized. Data stays on your machine; it does not pass through freeos.cnxy.tech.",
        },
        {
          q: "Do high-risk tools actually block?",
          a: "Yes. Outbound, delete, pay, and prod default-deny. execute becomes true only after a human approves that same action. A down sidecar does not fail open.",
        },
        {
          q: "Which license applies?",
          a: "The host and bridge are MIT. The vendored modules/openxyos tree is Apache-2.0. See NOTICE in the repository and keep copyright and license texts.",
        },
        {
          q: "Can I use it without Windows?",
          a: "Yes. From source: uv run freeos init && uv run freeos run. macOS and Linux desktop builds are on the same release. This page leads with Windows because that is the non-developer path.",
        },
      ],
    },
    cta: {
      title: "Grow an AI workforce on your own computer",
      lead: "Read the product at freeos.cnxy.tech, download from GitHub, or run the org loop from source. Visible, verifiable, decidable at every step.",
      download: "Download installer",
      github: "Star / Fork",
      openxyos: "About openXYOS",
    },
    footer: {
      blurb: "A self-hosted multi-agent OS that grows its own AI workforce. Official site: freeos.cnxy.tech.",
      product: "Product",
      home: "Website",
      legal: "License & credit",
      links: {
        releases: "Releases",
        contract: "Product contract",
        docs: "Architecture",
        loop: "Loop guide",
        notice: "NOTICE",
        octop: "Octop upstream (MIT)",
        openxyos: "openXYOS (Apache-2.0)",
      },
      attrib:
        "With thanks to Octop contributors (MIT) for the multi-agent runtime, and to openXYOS contributors (Apache-2.0) for organization capabilities. FreeOS is an independently maintained downstream project: we keep upstream licenses and NOTICE. Remaining octop identifiers are compatibility aliases.",
      copyright: "© 2026 XYAI Labs and FreeOS contributors",
    },
  },
} as const;
