export type Locale = "zh" | "en";

export const LINKS = {
  github: "https://github.com/XYAIStudio/FreeOS",
  releases: "https://github.com/XYAIStudio/FreeOS/releases/latest",
  releaseTag: "https://github.com/XYAIStudio/FreeOS/releases/tag/v0.0.1",
  windowsAmd64:
    "https://github.com/XYAIStudio/FreeOS/releases/download/v0.0.1/FreeOS-desktop-windows-amd64-0.0.1.exe",
  windowsArm64:
    "https://github.com/XYAIStudio/FreeOS/releases/download/v0.0.1/FreeOS-desktop-windows-arm64-0.0.1.exe",
  openxyos: "https://github.com/XYAIStudio/openXYOS",
  openxyosSite: "https://openxyos.cnxy.tech/?lang=zh-CN",
  octopUpstream: "https://github.com/TencentCloud/Octop",
  notice: "https://github.com/XYAIStudio/FreeOS/blob/main/NOTICE",
  architecture:
    "https://github.com/XYAIStudio/FreeOS/blob/main/docs/architecture-integration.md",
  assetLoop: "https://github.com/XYAIStudio/FreeOS/blob/main/docs/asset-loop.md",
} as const;

export const copy = {
  zh: {
    langName: "中文",
    skip: "跳到正文",
    nav: {
      engines: "双引擎",
      capabilities: "能力",
      download: "下载",
      loop: "自生长",
      faq: "问答",
    },
    brandAlt: "FreeOS 圆形标志：灰环、黄绿红勾玉、蓝色水滴",
    hero: {
      eyebrow: "开源 · 自托管 · v0.0.1",
      title: "FreeOS",
      promise: "懂你、帮你、陪你成长的智能伙伴",
      times: "×",
      org: "人机共融组织操作系统",
      lead: "在你自己的机器上，同时拥有会陪伴的个人智能体，和能养出 AI 员工队伍的组织操作系统。数据面跑起来，控制面长起来，一条闭环自己生长。",
      download: "下载 Windows 安装包",
      github: "打开 GitHub",
      chips: ["打开即可聊天，保存时再登录", "MIT + Apache-2.0", "组织控制台已内置"],
      mascotHint: "点一下换个姿态",
      mascotAlt: "XYAI 机器人欢迎姿态",
    },
    engines: {
      kicker: "双引擎 / 双循环",
      title: "数据面负责跑起来，控制面负责长起来",
      lead: "FreeOS 不是 Octop，也不是 openXYOS 的换皮。它把两条开源血统接成互补：一边生产会干活的智能体，一边用组织蓝图、治理和人才市场把它们养大，再喂回运行时。",
      dataTitle: "FreeOS 数据面",
      dataLicense: "MIT · 源自 Octop 运行时",
      dataBody: "多智能体聊天、技能、插件、MCP、记忆、定时任务、工作区与飞书 / 钉钉 / Discord 等 IM——真正把同事跑起来的那一层。",
      controlTitle: "openXYOS 控制面",
      controlLicense: "Apache-2.0 · 组织操作系统",
      controlBody: "多租户、组织建模、模块目录、智能体蓝图、治理引擎与人才市场——决定谁能进组织、能做什么、如何升级。",
      flowOut: "生产 AI 员工 · 技能 · 插件 · MCP",
      flowAssemble: "装配进 openXYOS 模块与人才市场",
      flowBack: "蓝图 · 治理 · 人才回馈",
      flowSpawn: "再孵化或升级运行时智能体",
      note: "两边互不替代：openXYOS 不接管聊天，FreeOS 不假装自己是上游商标。",
    },
    capabilities: {
      kicker: "能力",
      title: "个人伙伴的手，组织操作系统的骨",
      lead: "灵感来自陪伴型助手与人机共融组织 OS，但全部用 FreeOS 自己的语言来说。",
      groups: [
        {
          title: "数据面 · 把智能体跑在你机器上",
          items: [
            { name: "多智能体", text: "每位用户可养多位同事：独立工作区、模型、人格与对话。" },
            { name: "技能与插件", text: "SKILL.md、专家库、第三方插件，把一次性对话沉淀成可复用能力。" },
            { name: "MCP / 连接器", text: "OAuth 与 MCP 网关接入外部服务，工具走同一条审批路径。" },
            { name: "记忆与定时任务", text: "记忆随工作区迁移；Cron 把值班、汇报、巡检交给数字同事。" },
            { name: "IM 通道", text: "飞书、钉钉、QQ、Discord、企业微信与控制台共用一条处理链路。" },
          ],
        },
        {
          title: "控制面 · 把同事放进可治理的组织",
          items: [
            { name: "组织蓝图", text: "openxyos.agent-blueprint.v1 编译成可聊天的 FreeOS 智能体。" },
            { name: "治理与审批", text: "出站、删除、支付、生产变更默认拒绝，人批准后才 execute=true。" },
            { name: "模块目录", text: "按租户启停模块；技能可发布为草稿，从不自动上线。" },
            { name: "人才市场", text: "数字同事沿 draft → market → recruit → shadow → active 成长。" },
            { name: "租户隔离", text: "一个租户一套工作区 / 沙箱，不靠提示词假装隔离。" },
          ],
        },
      ],
    },
    download: {
      kicker: "下载 / 安装",
      title: "Windows 用户：下载、安装、打开即用",
      lead: "给非开发者的路径。安装包内置组织控制台，不必再装 Node。第一次启动会解压内置环境，可能要一两分钟。",
      amd64: "Windows 64 位",
      amd64Meta: "amd64 · .exe 安装包",
      arm64: "Windows ARM",
      arm64Meta: "arm64 · Surface / ARM 电脑",
      allReleases: "查看全部 Releases",
      stepsTitle: "四步开始",
      steps: [
        "打开 v0.0.1 Release，下载 amd64 或 arm64 安装包。",
        "双击安装。程序会写入「程序文件」，并创建开始菜单与桌面快捷方式。",
        "打开 FreeOS。解压完成后直接进入可用会话——先聊，不必先登录。",
        "保存、导出或发布到账号时再注册。侧栏 Organization 默认打开。",
      ],
      dataNote: "数据默认在 %USERPROFILE%\\.freeos（可用 FREEOS_HOME 改）。卸载不会删除用户数据目录。",
      cliTitle: "开发者：一条命令跑通闭环",
      cliHint: "克隆仓库后：",
    },
    loop: {
      kicker: "自生长闭环",
      title: "组织会自己长出下一位同事",
      lead: "freeos org loop run 是产品路径，不是演示脚本。它把蓝图变成可聊天的员工，走完生命周期，再把资产装回控制面，并证明高风险工具仍然被拦住。",
      steps: [
        { title: "生产", text: "数据面产出 AI 员工、技能、插件和 MCP，注册成真正能在聊天里叫到的智能体。" },
        { title: "装配", text: "资产打成 freeos.asset-pack.v1，写入 openXYOS 形状的员工、人才、插件与模块草稿。" },
        { title: "回馈", text: "组织树、蓝图、治理策略、模块目录和人才市场再进口到 FreeOS。" },
        { title: "升级", text: "下一位同事被孵化或升档。循环可重复，每次多一点可用能力。" },
      ],
      lifeTitle: "数字同事怎么转正",
      life: ["草稿", "上市", "招募", "见习", "在职", "离任"],
      lifeNote: "见习只读并受治理；转正后才打开岗位定时任务。离任会收回密钥，并把记忆归档到组织知识库。",
    },
    faq: {
      kicker: "问答",
      title: "先把关系讲清楚",
      items: [
        {
          q: "FreeOS 和 Octop、openXYOS 是什么关系？",
          a: "FreeOS 是独立开源宿主。数据面从 Octop（MIT）派生，控制面来自 openXYOS（Apache-2.0）。它们互补，不是互相换皮。FreeOS 不隶属、不代言腾讯云、Octop 或 XYOS 商标。",
        },
        {
          q: "Windows 打开后为什么不用登录？",
          a: "第一次进入是本地可用会话。聊天、试用组织能力不必先注册。只有保存、导出或发布到账号时才需要登录。",
        },
        {
          q: "我的对话和文件存在哪？",
          a: "默认 %USERPROFILE%\\.freeos。旧版 ~/.octop 仍会被识别。数据留在你的机器上，不经过 FreeOS 官网。",
        },
        {
          q: "高风险操作真的会被拦住吗？",
          a: "会。出站、删除、支付、生产变更默认拒绝。必须有人批准同一条动作，execute 才会变成 true。侧车宕机也不会放行。",
        },
        {
          q: "许可证怎么选？",
          a: "宿主与桥接代码是 MIT；vendored 的 modules/openxyos 是 Apache-2.0。完整声明见仓库 NOTICE，请保留版权与许可文本。",
        },
        {
          q: "没有 Windows 也能用吗？",
          a: "可以。仓库提供源码路径：uv run freeos init && uv run freeos run。macOS / Linux 桌面包也在同一 Release。官网把 Windows 安装包放在最前面，因为那是非开发者的主路径。",
        },
      ],
    },
    cta: {
      title: "在自己的电脑上，养一支会成长的 AI 队伍",
      lead: "下载安装包，或从源码跑通 org loop。控制面的上游项目是 openXYOS。",
      download: "下载 v0.0.1",
      github: "Star / Fork",
      openxyos: "了解 openXYOS",
    },
    footer: {
      blurb: "自托管多智能体 OS，能生产并回收自己的 AI 员工。",
      product: "产品",
      legal: "许可与致谢",
      links: {
        releases: "Releases",
        docs: "集成架构",
        loop: "闭环说明",
        notice: "NOTICE",
        octop: "Octop 上游（MIT）",
        openxyos: "openXYOS（Apache-2.0）",
      },
      attrib:
        "数据面派生自 Octop（MIT，Copyright Octop contributors）。控制面来自 openXYOS（Apache-2.0，Copyright Xiongyuan Technology and XYOS contributors）。FreeOS 是独立项目，不主张与腾讯云、Tencent、Octop、XYAIStudio 或 XYOS 的商标从属关系。残留的 octop 标识符仅为兼容别名。",
      copyright: "© 2026 XYAI Labs 与 FreeOS 贡献者",
    },
  },
  en: {
    langName: "EN",
    skip: "Skip to content",
    nav: {
      engines: "Engines",
      capabilities: "Capabilities",
      download: "Download",
      loop: "The loop",
      faq: "FAQ",
    },
    brandAlt: "FreeOS circular mark: gray ring, yellow green red magatama, blue teardrop",
    hero: {
      eyebrow: "Open source · Self-hosted · v0.0.1",
      title: "FreeOS",
      promise: "Understands you, helps you, grows with you",
      times: "×",
      org: "an OS for human–AI organizations",
      lead: "On your own machine: a personal AI partner and an organization OS that grows its own AI workforce. The data plane runs colleagues. The control plane raises them. The loop feeds itself.",
      download: "Download for Windows",
      github: "View GitHub",
      chips: ["Chat first, sign in when you save", "MIT + Apache-2.0", "Organization console bundled"],
      mascotHint: "Tap to switch pose",
      mascotAlt: "XYAI robot in the welcome pose",
    },
    engines: {
      kicker: "Two engines / two loops",
      title: "The data plane runs. The control plane grows.",
      lead: "FreeOS is not Octop and not a reskin of openXYOS. It joins two open-source lineages: one produces working agents, the other raises them with blueprints, governance, and a talent market, then feeds them back.",
      dataTitle: "FreeOS data plane",
      dataLicense: "MIT · derived from the Octop runtime",
      dataBody: "Multi-agent chat, skills, plugins, MCP, memory, cron, workspaces, and IM channels such as Feishu, DingTalk, and Discord — the layer that actually runs colleagues.",
      controlTitle: "openXYOS control plane",
      controlLicense: "Apache-2.0 · organization OS",
      controlBody: "Multi-tenancy, org modeling, module catalog, agent blueprints, governance, and the talent market — who joins, what they may do, how they level up.",
      flowOut: "Produce employees, skills, plugins, MCP",
      flowAssemble: "Assemble into openXYOS modules and talent",
      flowBack: "Blueprints, governance, talent feed back",
      flowSpawn: "Spawn or upgrade runtime agents",
      note: "Neither side replaces the other. openXYOS does not take over chat. FreeOS does not claim upstream trademarks.",
    },
    capabilities: {
      kicker: "Capabilities",
      title: "A companion’s hands. An organization OS’s bones.",
      lead: "Inspired by companion assistants and human–AI organization systems — spoken in FreeOS’s own voice.",
      groups: [
        {
          title: "Data plane · agents on your machine",
          items: [
            { name: "Multi-agent", text: "Each user can raise several colleagues, each with a workspace, model, persona, and threads." },
            { name: "Skills & plugins", text: "SKILL.md, an expert library, and third-party plugins turn one-off chats into reusable capability." },
            { name: "MCP / connectors", text: "OAuth and an MCP gateway reach external services. Tools share one approval path." },
            { name: "Memory & cron", text: "Memory travels with the workspace. Cron hands patrols, reports, and shifts to digital colleagues." },
            { name: "IM channels", text: "Feishu, DingTalk, QQ, Discord, WeCom, and the console share one processing pipeline." },
          ],
        },
        {
          title: "Control plane · colleagues inside a governed org",
          items: [
            { name: "Org blueprints", text: "openxyos.agent-blueprint.v1 compiles into chat-ready FreeOS agents." },
            { name: "Governance", text: "Outbound, delete, pay, and prod stay denied until a human approves the same action digest." },
            { name: "Module catalog", text: "Enable modules per tenant. Published skills stay drafts — never auto-on." },
            { name: "Talent market", text: "Colleagues grow draft → market → recruit → shadow → active." },
            { name: "Tenant isolation", text: "One tenant, one workspace/sandbox. Prompts are not a tenancy boundary." },
          ],
        },
      ],
    },
    download: {
      kicker: "Download / install",
      title: "Windows: download, install, open, and use",
      lead: "The non-developer path. The installer bundles the organization console — no extra Node install. First launch unpacks a runtime and may take a minute or two.",
      amd64: "Windows 64-bit",
      amd64Meta: "amd64 · .exe installer",
      arm64: "Windows ARM",
      arm64Meta: "arm64 · Surface and ARM PCs",
      allReleases: "All releases",
      stepsTitle: "Four steps",
      steps: [
        "Open the v0.0.1 release and download the amd64 or arm64 installer.",
        "Run it. Files land in Program Files, with Start Menu and desktop shortcuts.",
        "Open FreeOS. After unpacking you land in a usable session — chat first, no login.",
        "Register only when you save, export, or publish to an account. Organization is on by default.",
      ],
      dataNote: "Data lives in %USERPROFILE%\\.freeos (override with FREEOS_HOME). Uninstall does not delete that directory.",
      cliTitle: "Developers: run the loop in one command",
      cliHint: "After cloning the repo:",
    },
    loop: {
      kicker: "Self-growth loop",
      title: "The organization grows its next colleague",
      lead: "freeos org loop run is the product path, not a demo. It turns a blueprint into a chat-addressable employee, walks the lifecycle, applies assets back to the control plane, and proves high-risk tools still stop.",
      steps: [
        { title: "Produce", text: "The data plane emits employees, skills, plugins, and MCP, registered as real chat agents." },
        { title: "Assemble", text: "Packs become freeos.asset-pack.v1 and land on openXYOS-shaped employee, talent, plugin, and module drafts." },
        { title: "Feed back", text: "Org tree, blueprints, policies, the module catalog, and talent import back into FreeOS." },
        { title: "Upgrade", text: "The next colleague is spawned or promoted. Repeat. Each cycle adds usable capability." },
      ],
      lifeTitle: "How a digital colleague is promoted",
      life: ["Draft", "Market", "Recruit", "Shadow", "Active", "Offboard"],
      lifeNote: "Shadow is read-only and governed. Cron from job duties turns on only when active. Offboard revokes secrets and archives memory into org knowledge.",
    },
    faq: {
      kicker: "FAQ",
      title: "The relationships, plainly",
      items: [
        {
          q: "How does FreeOS relate to Octop and openXYOS?",
          a: "FreeOS is an independent host. The data plane is derived from Octop (MIT). The control plane comes from openXYOS (Apache-2.0). They complement each other. FreeOS is not affiliated with, endorsed by, or a trademark stand-in for Tencent Cloud, Octop, or XYOS.",
        },
        {
          q: "Why is there no login on first launch?",
          a: "The first session is local and ready. Chat and try organization features without registering. Sign in only when you save, export, or publish to an account.",
        },
        {
          q: "Where do chats and files live?",
          a: "Default %USERPROFILE%\\.freeos. Legacy ~/.octop is still recognized. Data stays on your machine; it does not pass through this website.",
        },
        {
          q: "Do high-risk tools actually block?",
          a: "Yes. Outbound, delete, pay, and prod default-deny. execute becomes true only after a human approves that same action. A down sidecar does not fail open.",
        },
        {
          q: "Which license applies?",
          a: "The host and bridge are MIT. The vendored modules/openxyos tree is Apache-2.0. See NOTICE in the repository and keep copyright and license texts.",
        },
        {
          q: "Can I use it without Windows?",
          a: "Yes. From source: uv run freeos init && uv run freeos run. macOS and Linux desktop builds are on the same release. This page leads with Windows because that is the non-developer path.",
        },
      ],
    },
    cta: {
      title: "Grow an AI workforce on your own computer",
      lead: "Download the installer, or run the org loop from source. The upstream control plane is openXYOS.",
      download: "Download v0.0.1",
      github: "Star / Fork",
      openxyos: "About openXYOS",
    },
    footer: {
      blurb: "A self-hosted multi-agent OS that grows its own AI workforce.",
      product: "Product",
      legal: "License & credit",
      links: {
        releases: "Releases",
        docs: "Architecture",
        loop: "Loop guide",
        notice: "NOTICE",
        octop: "Octop upstream (MIT)",
        openxyos: "openXYOS (Apache-2.0)",
      },
      attrib:
        "Data plane derived from Octop (MIT, Copyright Octop contributors). Control plane from openXYOS (Apache-2.0, Copyright Xiongyuan Technology and XYOS contributors). FreeOS is independent and claims no affiliation with Tencent Cloud, Tencent, Octop, XYAIStudio, or XYOS trademarks. Remaining octop identifiers are compatibility aliases.",
      copyright: "© 2026 XYAI Labs and FreeOS contributors",
    },
  },
} as const;
