import type { OrgLocale } from "../../shell";

const EN = {
  title: "Workspace",
  subtitle:
    "Organization landing overview. Status and links into already-migrated pages — not a second control plane.",
  hostHint:
    "Assemble, pack, and the growth loop stay on the Organization workbench. This page only summarizes host status.",
  notHereTitle: "Chat is not here",
  notHereBody:
    "openXYOS Chat is not migrated. Conversations stay on FreeOS / Octop. This overview does not open a sidecar inbox.",
  openChat: "FreeOS conversations",
  openWorkbench: "Organization workbench",
  statusTitle: "Organization status",
  enabled: "On",
  disabled: "Off",
  inHost: "In-host",
  tenant: "Tenant",
  lastSync: "Last sync",
  neverSynced: "Never",
  colleagues: "Colleagues",
  spawned: "Spawned agents",
  skills: "Org skills",
  modules: "Catalog modules",
  talent: "Talent",
  pauses: "Pending pauses",
  pauseBanner: "{count} governance pause(s) waiting.",
  pauseBannerAction: "Review pauses",
  roomHint:
    "This overview is the organization room. Everyday studio chat stays a separate space.",
  modulesTitle: "Open pages",
  modulesHint:
    "Same host pages Dashboard mounts under Organization. Chat is intentionally absent.",
  loading: "Loading organization overview…",
  loadFailed: "Could not load organization overview",
  emptyCatalog: "No enabled organization pages.",
  announcements: "Announcements",
  announcementsBody: "Publish notices and track who has read them.",
  organization: "Organization chart",
  organizationBody: "Departments and people on the host org tree.",
  employees: "Employees",
  employeesBody: "Directory of people and AI colleagues, plus the host talent market.",
  skillsPage: "Skills",
  skillsBody: "Generated org-API skill wrappers. Agent Skills stay on FreeOS.",
  agents: "Agent Studio",
  agentsBody: "Compile digital colleagues and manage lifecycle.",
  tasks: "Tasks",
  tasksBody: "Organization work items. Not cron and not chat.",
  knowledge: "Knowledge",
  knowledgeBody: "The same FreeOS knowledge bases Chat retrieves from.",
  reflections: "Reflections",
  reflectionsBody: "Lessons learned on the host org store.",
  governance: "Governance",
  governanceBody: "Pending approvals and the host audit log.",
  settings: "Settings",
  settingsBody: "Catalog toggles and org-local preferences.",
};

const ZH: typeof EN = {
  title: "工作台总览",
  subtitle: "组织落地页：状态摘要，并链到已迁入宿主的子页。不是第二套控制面。",
  hostHint: "装配、打包和自增长循环仍在组织工作台。本页只汇总宿主状态。",
  notHereTitle: "对话不在这里",
  notHereBody:
    "openXYOS Chat 不迁入。对话留在 FreeOS / Octop。本页不会打开边车收件箱。",
  openChat: "FreeOS 对话",
  openWorkbench: "组织工作台",
  statusTitle: "组织状态",
  enabled: "已启用",
  disabled: "未启用",
  inHost: "宿主内",
  tenant: "租户",
  lastSync: "最近同步",
  neverSynced: "尚未同步",
  colleagues: "数字同事",
  spawned: "已注册智能体",
  skills: "组织技能",
  modules: "目录模块",
  talent: "人才",
  pauses: "待处理暂停",
  pauseBanner: "有 {count} 条治理暂停待处理。",
  pauseBannerAction: "去处理",
  roomHint: "本页是组织房间总览。日常工作室对话仍是另一套空间。",
  modulesTitle: "已迁页面",
  modulesHint: "与 Dashboard Organization 下同一套宿主页。对话故意不在此列。",
  loading: "正在加载组织总览…",
  loadFailed: "无法加载组织总览",
  emptyCatalog: "没有已启用的组织页面。",
  announcements: "通知公告",
  announcementsBody: "发布公告并跟踪已读。",
  organization: "组织架构",
  organizationBody: "宿主组织树上的部门与人员。",
  employees: "员工目录",
  employeesBody: "人机员工名册，以及宿主人才市场。",
  skillsPage: "技能",
  skillsBody: "组织 API 的生成包装。Agent Skills 仍在 FreeOS。",
  agents: "智能体定制",
  agentsBody: "编译数字同事并管理生命周期。",
  tasks: "任务",
  tasksBody: "组织待办。不是定时任务，也不是对话。",
  knowledge: "知识",
  knowledgeBody: "Chat 检索用的同一套 FreeOS 知识库。",
  reflections: "反思",
  reflectionsBody: "宿主组织库里的复盘与经验。",
  governance: "治理",
  governanceBody: "待审批与宿主审计日志。",
  settings: "设置",
  settingsBody: "目录开关与组织本地偏好。",
};

export type WorkspaceLabels = typeof EN;

export function workspaceLabels(locale: OrgLocale): WorkspaceLabels {
  return locale === "zh" ? ZH : EN;
}
