import type { OrgLocale } from "../../shell";

const EN = {
  title: "Tasks",
  subtitle:
    "Organization work items on the host. Stored under FREEOS_HOME/org — not Octop cron, not project chat, and not a sidecar.",
  hostHint:
    "These are org tasks (todo → done). Scheduled agent jobs stay on Cron. Agent conversation stays on Chat.",
  search: "Search tasks…",
  loading: "Loading tasks…",
  empty: "No tasks yet.",
  emptyHint: "Create a task here. It stays on the host org store.",
  noMatch: "No tasks match this filter",
  create: "Create task",
  createTitle: "Create a task",
  refresh: "Refresh",
  fieldTitle: "Title",
  fieldDescription: "Description",
  fieldPriority: "Priority",
  required: "Title is required",
  cancel: "Cancel",
  save: "Save",
  edit: "Edit",
  delete: "Delete",
  confirmDelete: "Delete this task?",
  back: "Back to tasks",
  notFound: "Task not found",
  total: "Total",
  filter: "Filter",
  all: "All",
  status: "Status",
  todo: "To do",
  inProgress: "In progress",
  review: "In review",
  done: "Done",
  start: "Start",
  submit: "Submit",
  approve: "Approve",
  startWork: "Start work",
  submitReview: "Submit for review",
  approveReview: "Approve review",
  completed: "Task completed",
  priorityLow: "Low",
  priorityMedium: "Medium",
  priorityHigh: "High",
  priorityCritical: "Critical",
  subtasks: "Subtasks",
  addSubtask: "Add a subtask…",
  comments: "Comments",
  addComment: "Add a comment…",
  commentHint: "Human notes on this work item. This is not agent chat.",
  createdBy: "Created by",
  createdAt: "Created",
  unknown: "Unknown",
  unassigned: "Unassigned",
  assignee: "Assignee",
  basic: "Task",
};

const ZH: typeof EN = {
  title: "任务",
  subtitle:
    "宿主内的组织待办。存在 FREEOS_HOME/org，不是 Octop 定时任务，也不是项目对话或边车。",
  hostHint:
    "这里是组织任务（待办 → 完成）。定时智能体作业仍在「定时任务」。对话仍在 Chat。",
  search: "搜索任务…",
  loading: "加载任务…",
  empty: "还没有任务。",
  emptyHint: "在这里创建任务，数据留在宿主组织库。",
  noMatch: "没有匹配的任务",
  create: "创建任务",
  createTitle: "创建新任务",
  refresh: "刷新",
  fieldTitle: "标题",
  fieldDescription: "描述",
  fieldPriority: "优先级",
  required: "标题不能为空",
  cancel: "取消",
  save: "保存",
  edit: "编辑",
  delete: "删除",
  confirmDelete: "确定删除此任务？",
  back: "返回任务列表",
  notFound: "任务不存在",
  total: "合计",
  filter: "筛选",
  all: "全部",
  status: "状态",
  todo: "待办",
  inProgress: "进行中",
  review: "评审中",
  done: "已完成",
  start: "执行",
  submit: "提交",
  approve: "通过",
  startWork: "开始执行",
  submitReview: "提交评审",
  approveReview: "评审通过",
  completed: "任务已完成",
  priorityLow: "低",
  priorityMedium: "中",
  priorityHigh: "高",
  priorityCritical: "紧急",
  subtasks: "子任务",
  addSubtask: "添加子任务…",
  comments: "评论",
  addComment: "添加评论…",
  commentHint: "这是工作项上的人工备注，不是智能体对话。",
  createdBy: "创建者",
  createdAt: "创建时间",
  unknown: "未知",
  unassigned: "待分配",
  assignee: "负责人",
  basic: "任务",
};

export type TaskLabels = typeof EN;

export function taskLabels(locale: OrgLocale): TaskLabels {
  return locale === "zh" ? ZH : EN;
}
