import type { OrgLocale } from "../../shell";

const EN = {
  title: "Employees",
  subtitle:
    "People already in a department, plus the host talent market. Same sqlite as the org chart — no Node hop.",
  tabDirectory: "Directory",
  tabTalent: "Talent market",
  talentSubtitle:
    "Available talent from the asset bus and Agent Studio. Recruit writes the host directory and lifecycle.",
  talentEmpty:
    "No talent on the host market yet. Pack or loop assets to land rows here.",
  talentRecruit: "Recruit",
  talentRecruited: "Recruited into the directory",
  talentLoadFailed: "Could not load talent",
  talentRecruitFailed: "Could not recruit this talent",
  search: "Search name, role, or skills...",
  loading: "Loading employees...",
  empty: "No employees yet. Add a person after a department exists.",
  emptyHint:
    "Create a department on the org chart first, then add people here.",
  add: "New employee",
  allTypes: "All types",
  typeHuman: "Human",
  typeAi: "AI colleague",
  fieldName: "Name",
  fieldRole: "Role",
  fieldDescription: "Responsibilities",
  fieldType: "Type",
  fieldDepartment: "Department",
  fieldSkills: "Skills",
  fieldSkillsHint: "Comma-separated tags",
  fieldEmoji: "Avatar",
  noRole: "No role assigned",
  noDepartment: "Unassigned",
  noSkills: "No skill tags",
  noDescription: "No responsibilities have been set",
  save: "Save",
  create: "Create",
  cancel: "Cancel",
  edit: "Edit",
  deactivate: "Deactivate",
  confirmDeactivate:
    "Deactivate this employee? They leave the active directory.",
  required: "Name and department are required",
  noMatch: "No people match this filter",
  total: "Total",
  back: "Back to directory",
  notFound: "Employee not found",
  basic: "Basic information",
  details: "Profile",
};

const ZH: typeof EN = {
  title: "员工目录",
  subtitle:
    "已入编部门的人机员工，以及宿主人才市场。与组织架构同一份 sqlite，不经过 Node。",
  tabDirectory: "在职名册",
  tabTalent: "人才市场",
  talentSubtitle:
    "资产总线与智能体定制落到宿主的待招人才。招募会写入名册和生命周期。",
  talentEmpty: "宿主人才市场还是空的。打包或运行循环后会出现在这里。",
  talentRecruit: "招募",
  talentRecruited: "已招募进名册",
  talentLoadFailed: "无法加载人才市场",
  talentRecruitFailed: "招募失败",
  search: "搜索姓名、岗位或技能...",
  loading: "加载员工...",
  empty: "还没有员工。先有部门后再添加人员。",
  emptyHint: "请先在组织架构中创建部门，再回到这里加人。",
  add: "新建员工",
  allTypes: "全部类型",
  typeHuman: "人类",
  typeAi: "AI 同事",
  fieldName: "姓名",
  fieldRole: "岗位",
  fieldDescription: "岗位职责",
  fieldType: "类型",
  fieldDepartment: "部门",
  fieldSkills: "技能",
  fieldSkillsHint: "逗号分隔的标签",
  fieldEmoji: "头像",
  noRole: "未分配岗位",
  noDepartment: "未分配",
  noSkills: "暂无技能标签",
  noDescription: "暂未设置岗位职责",
  save: "保存",
  create: "创建",
  cancel: "取消",
  edit: "编辑",
  deactivate: "停用",
  confirmDeactivate: "确定停用该员工？停用后会离开在职名册。",
  required: "姓名和部门不能为空",
  noMatch: "没有匹配的人员",
  total: "合计",
  back: "返回名册",
  notFound: "未找到该员工",
  basic: "基本信息",
  details: "资料",
};

export type EmployeeLabels = typeof EN;

export function employeeLabels(locale: OrgLocale): EmployeeLabels {
  return locale === "zh" ? ZH : EN;
}
