import type { OrgLocale } from "../../shell";

const EN = {
  title: "Employees",
  subtitle: "People and AI colleagues on the host org directory.",
  search: "Search name, role, or skills...",
  loading: "Loading employees...",
  empty: "No employees yet. Add a person after a department exists.",
  emptyHint:
    "Create a department on the org chart first, then add people here.",
  add: "New employee",
  allTypes: "All types",
  typeHuman: "Human",
  typeAi: "AI colleague",
  fieldName: "Name",
  fieldRole: "Role",
  fieldDescription: "Responsibilities",
  fieldType: "Type",
  fieldDepartment: "Department",
  fieldSkills: "Skills",
  fieldSkillsHint: "Comma-separated tags",
  fieldEmoji: "Avatar",
  noRole: "No role assigned",
  noDepartment: "Unassigned",
  noSkills: "No skill tags",
  noDescription: "No responsibilities have been set",
  save: "Save",
  create: "Create",
  cancel: "Cancel",
  edit: "Edit",
  deactivate: "Deactivate",
  confirmDeactivate:
    "Deactivate this employee? They leave the active directory.",
  required: "Name and department are required",
  noMatch: "No people match this filter",
  total: "Total",
  back: "Back to directory",
  notFound: "Employee not found",
  basic: "Basic information",
  details: "Profile",
};

const ZH: typeof EN = {
  title: "员工目录",
  subtitle: "宿主内的人机员工名册。",
  search: "搜索姓名、岗位或技能...",
  loading: "加载员工...",
  empty: "还没有员工。先有部门后再添加人员。",
  emptyHint: "请先在组织架构中创建部门，再回到这里加人。",
  add: "新建员工",
  allTypes: "全部类型",
  typeHuman: "人类",
  typeAi: "AI 同事",
  fieldName: "姓名",
  fieldRole: "岗位",
  fieldDescription: "岗位职责",
  fieldType: "类型",
  fieldDepartment: "部门",
  fieldSkills: "技能",
  fieldSkillsHint: "逗号分隔的标签",
  fieldEmoji: "头像",
  noRole: "未分配岗位",
  noDepartment: "未分配",
  noSkills: "暂无技能标签",
  noDescription: "暂未设置岗位职责",
  save: "保存",
  create: "创建",
  cancel: "取消",
  edit: "编辑",
  deactivate: "停用",
  confirmDeactivate: "确定停用该员工？停用后会离开在职名册。",
  required: "姓名和部门不能为空",
  noMatch: "没有匹配的人员",
  total: "合计",
  back: "返回名册",
  notFound: "未找到该员工",
  basic: "基本信息",
  details: "资料",
};

export type EmployeeLabels = typeof EN;

export function employeeLabels(locale: OrgLocale): EmployeeLabels {
  return locale === "zh" ? ZH : EN;
}
