package main

import (
	"testing"
	"time"
)

func TestDarwinTrayLeftClickShowsSettings(t *testing.T) {
	if !trayLeftClickShowsSettings("darwin") {
		t.Fatal("macOS menu-bar click should open the settings popover")
	}
}

func TestNonDarwinTrayLeftClickDoesNotShowSettings(t *testing.T) {
	for _, goos := range []string{"windows", "linux"} {
		if trayLeftClickShowsSettings(goos) {
			t.Fatalf("%s left-click should restore the main window, not the settings popover", goos)
		}
	}
}

func TestTrayHideClosingIsConsumedOnce(t *testing.T) {
	app := &App{trayHidePending: true}
	if !app.consumeTrayHideClosing() {
		t.Fatal("the closing event generated by hiding to tray should be consumed")
	}
	if app.consumeTrayHideClosing() {
		t.Fatal("a later user close must not be mistaken for the tray-hide event")
	}
}

func TestWindowRestoreIgnoresDelayedMinimiseEvent(t *testing.T) {
	now := time.Now()
	app := &App{trayHidePending: true, trayHideGeneration: 4}
	generation := app.beginWindowRestore(now)

	if app.trayHidePending {
		t.Fatal("restoring must cancel a pending hide-to-tray close event")
	}
	if app.trayHideGeneration != 5 {
		t.Fatal("restoring must invalidate the pending hide-to-tray timeout")
	}
	if !app.windowRestoreInProgress(now.Add(windowRestoreGrace - time.Millisecond)) {
		t.Fatal("a delayed minimise event must be ignored during restore")
	}
	if app.windowRestoreInProgress(now.Add(windowRestoreGrace)) {
		t.Fatal("a later user minimise must not be ignored")
	}
	if !app.windowRestoreCurrent(generation, now.Add(time.Second)) {
		t.Fatal("scheduled restore attempts must remain active during the grace period")
	}
	if app.windowRestoreCurrent(generation+1, now.Add(time.Second)) {
		t.Fatal("stale restore attempts must not affect a newer restore")
	}
}
